### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by shirshak55**
Goals:
1. Add various versions available in Linux
2.  esm only over common js.
3. Improve testing
4. Add nodejs 16 and 17 to GitHub action
5. Improve code
6. Publish  only a small artifact to npm

Anyway, most of the decisions will always be made by the community so if anyone has any concerns please raise it. We will decide within 10-15 days. The goal here is to not create any churn in the ecosystem. 

Once I think the PR is ready I will call the team from dev tools to review it.

Thank you.

### CODE REVIEW

**Comment by shirshak55** [comment]
r? @christian-bromann 
Hi, Soft ping to you :)

Would you please review it before I publish the latest version to npm. Last time I caused quite a problem to you so this time I don't want to repeat it :+1:

**Comment by christian-bromann** [comment]
Thanks for pinging @shirshak55 .. the WebdriverIO project won't be able to use ESM only packages so we won't be able to update to v3. Please go ahead and release. I will come back if I see issues once we have a chance to upgrade to ESM as well.

**Comment by NightScript370** [comment]
Hello. I would like to use this package for my project but personally use Linux and would need to depend on this v3 update.
What is the likelihood of getting this PR merged?

**Comment by shirshak55** [comment]
@NightScript370 Alright, will publish it by tomorrow.

**Comment by shirshak55** [comment]
Done

**Comment by NightScript370** [comment]
Thank you! Looking forward to using it in Deno.

**Pull request merged**
