### PR TITLE
chore: add semantic commits and commitizen

### LINKED ISSUE #13: Semantic Versioning
# Semver Versioning

I know this may be a big ask, but... The release notes are bad. With Conventional Commits, users know what they're updating to and why the version was bumped up without having to view all your commits. 

Btw, great project! 

For an example, [view my project](https://github.com/BrycensRanch/Chatting-Platform). It automatically releases and generates informative changelogs via GitHub Actions

### PR DESCRIPTION
**Pull request by BrycensRanch**
# Semantic Version + Conventional Commits

This PR introduces the standardization of contributions to this repository. 

From now on, every commit to the repo should be able to be parsed by a robot with ease thanks to [Conventional Commits](https://www.conventionalcommits.org). Introduced a CONTRIBUTING.md so other contributors get the message as well. 

Added automatic GitHub releases and tags based on branch

Every new PR on this repo will have a semantic version check for the PR name, if it doesn't follow the standard, the check fails. However, nothing is stopping you from just merging anyway.

Added husky and commitlint to ensure developers use the standard. If they need to, they can always run 
```bash
git commit --no-verify -m "message"
```
But I highly doubt there's any use for that, considering that the commit hook runs extremely fast.

bunch of QoL extension recommendations as well

Closes #13 

## GitHub Actions Testing

Unfortunately, I didn't get a chance to test the newly added GitHub Actions locally due to the multi-platform tests, however, they work just fine in my repo, so it should work.

### CODE REVIEW

**Comment by shirshak55** [comment]
Thank You. I will take some time to review it and if everything goes okay we shall merge it soon.

**Comment by BrycensRanch** [comment]
btw I ran the tests without the broken macos tests and it works fine on my fork of the repo

**Comment by shirshak55** [comment]
@BrycensRanch the tests are passing atm.

**Comment by shirshak55** [comment]
Merged

**Comment by shirshak55** [comment]
Thank you

**Comment by BrycensRanch** [comment]
😎 another project added to the semantic release army 🚀

**Comment by BrycensRanch** [comment]
Oh yeah, forgot to specify that the release workflow should have permissions to roll out releases, npm releases are still manual, when I was first rolling out semantic release, a lot of unnecessary releases were created

**Comment by shirshak55** [comment]
Thats okay :) And, I will test the demo project before doing anything here.

**Pull request merged**
